GET http://marcing20067.pythonanywhere.com/tasks
###

POST http://marcing20067.pythonanywhere.com/tasks
Content-Type: application/json

{
    "content": "Ogarnij metodę PUT oraz literówki",
    "primary_task": 1,
    "hour": "8:00 - 9:00",
    "day_num": 12, 
    "month_num": 1,
    "year": 2021,
    "done": true
}

###
PUT http://localhost:5000/tasks/4
Content-Type: application/json

{
    "content": "Brzdąc sćąśąśżć",
    "hour": "8:00",
    "primary_task": 1,
    "day_num": 12, 
    "month_num": 1,
    "year": 2021
}

###
DELETE http://localhost:5000/tasks/9
